version: '3.8'

services:
  app:
    container_name: "travel-blog-server"
    image: maximko/travel-blog-server
    depends_on:
      - db
    env_file: ./server/.env
    restart: unless-stopped
  
  db:
    container_name: "travel-blog-postgres"
    image: postgres:14-alpine
    env_file: ./server/.env
    restart: unless-stopped
    volumes:
      - postgresDbData:/var/lib/postgresql/data

volumes: 
  postgresDbData: 


