version: '3.8'

services:
  app:
    container_name: "travel-blog-backend"
    image: maximko/travel-blog-backend
    depends_on:
      - db
    env_file: .env
    restart: unless-stopped
  
  db:
    container_name: "travel-blog-postgres"
    image: postgres:14-alpine
    env_file: .env
    restart: unless-stopped
    volumes:
      - postgresDb:/var/lib/postgresql/data

volumes: 
  postgresDb: 


