version: '3.8'

services:
  app:
    build: 
      context: .
      target: "dev"
    volumes:
      - type: bind
        source: ./src
        target: /app/src
    env_file: .env.development
    ports:
      - 8080:${NODE_PORT}
  
  db:
    env_file: .env.development
    ports:
      - 5433:5432

 

